# Generated by Django 2.0.4 on 2018-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('rut', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('position', models.CharField(choices=[('BASE', 'Base'), ('ESCOLTA', 'Escolta'), ('ALERO', 'Alero'), ('ALA_PIVOT', 'Ala-pivot'), ('PIVOT', 'Pivot')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
