# Generated by Django 2.0.4 on 2018-04-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
