# Generated by Django 2.0.4 on 2018-04-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea01', '0002_auto_20180420_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tarea01.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tarea01.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soccergame',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tarea01.Team'),
            preserve_default=False,
        ),
    ]
