# Generated by Django 2.0.4 on 2018-04-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea01', '0003_auto_20180420_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoccerGame',
            new_name='BasketGame',
        ),
    ]
